using System;
using System.Collections.Generic;
using UnityEngine;

public static class Permutations
{

    public static List<List<string>> List = new List<List<string>>
    {
        // 00
        new List<string> { "repos", "sentiment", "dictionnaire", "mémoire", "tableau", "façon", "piscine", "confiance", "méthode", "côté", "vaisselle", "calendrier", "poche", "sourire", "chance", "activité", "science", "centre", "chanson", "reste", "intelligence", "fromage", "chaleur", "lecture", "effort", "vacance", "importance", "fenêtre", "salaire", "gouvernement", "excuse", "programme", "escalier", "environnement", "avantage", "plaisir", "voiture", "boisson", "bouteille", "travailleur", "carotte", "différence", "raison", "explication" },
        // 01
        new List<string> { "différence", "reste", "chanson", "poche", "environnement", "fromage", "intelligence", "effort", "lecture", "repos", "tableau", "vaisselle", "travailleur", "piscine", "voiture", "plaisir", "gouvernement", "escalier", "fenêtre", "explication", "salaire", "vacance", "méthode", "façon", "dictionnaire", "côté", "centre", "boisson", "activité", "avantage", "excuse", "calendrier", "confiance", "sentiment", "bouteille", "programme", "importance", "chaleur", "mémoire", "carotte", "science", "raison", "sourire", "chance" },
        // 02
        new List<string> { "avantage", "vacance", "programme", "gouvernement", "vaisselle", "piscine", "lecture", "effort", "bouteille", "explication", "fenêtre", "fromage", "escalier", "calendrier", "dictionnaire", "intelligence", "voiture", "méthode", "raison", "sentiment", "poche", "confiance", "excuse", "salaire", "sourire", "plaisir", "activité", "mémoire", "science", "importance", "chance", "différence", "environnement", "centre", "travailleur", "chaleur", "côté", "repos", "reste", "façon", "boisson", "chanson", "tableau", "carotte" },
        // 03
        new List<string> { "lecture", "façon", "raison", "bouteille", "avantage", "tableau", "environnement", "plaisir", "chaleur", "science", "vaisselle", "travailleur", "vacance", "voiture", "sentiment", "côté", "mémoire", "dictionnaire", "sourire", "méthode", "gouvernement", "carotte", "chanson", "escalier", "excuse", "différence", "fenêtre", "salaire", "fromage", "boisson", "explication", "chance", "reste", "activité", "effort", "calendrier", "repos", "intelligence", "programme", "piscine", "poche", "centre", "confiance", "importance" },
        // 04
        new List<string> { "explication", "méthode", "côté", "intelligence", "travailleur", "sentiment", "différence", "tableau", "chaleur", "plaisir", "science", "poche", "voiture", "sourire", "importance", "calendrier", "dictionnaire", "piscine", "fromage", "excuse", "escalier", "activité", "gouvernement", "raison", "avantage", "environnement", "chance", "vaisselle", "reste", "programme", "salaire", "boisson", "fenêtre", "mémoire", "confiance", "centre", "lecture", "repos", "vacance", "façon", "carotte", "effort", "bouteille", "chanson" },
        // 05
        new List<string> { "sentiment", "chance", "chaleur", "environnement", "reste", "lecture", "voiture", "fenêtre", "repos", "côté", "différence", "boisson", "plaisir", "centre", "programme", "escalier", "intelligence", "science", "poche", "vacance", "gouvernement", "façon", "mémoire", "méthode", "carotte", "calendrier", "chanson", "activité", "raison", "bouteille", "avantage", "excuse", "tableau", "dictionnaire", "effort", "fromage", "confiance", "importance", "salaire", "piscine", "explication", "travailleur", "sourire", "vaisselle" },
        // 06
        new List<string> { "escalier", "côté", "poche", "effort", "boisson", "lecture", "intelligence", "travailleur", "gouvernement", "sourire", "calendrier", "dictionnaire", "sentiment", "reste", "chance", "importance", "différence", "plaisir", "programme", "centre", "science", "méthode", "chanson", "voiture", "façon", "environnement", "tableau", "activité", "vaisselle", "explication", "carotte", "fenêtre", "bouteille", "confiance", "repos", "salaire", "piscine", "chaleur", "avantage", "fromage", "excuse", "vacance", "raison", "mémoire" },
        // 07
        new List<string> { "chanson", "sentiment", "façon", "activité", "tableau", "reste", "programme", "bouteille", "calendrier", "excuse", "escalier", "science", "méthode", "raison", "chaleur", "fenêtre", "intelligence", "environnement", "côté", "voiture", "lecture", "plaisir", "travailleur", "vaisselle", "différence", "fromage", "centre", "sourire", "confiance", "gouvernement", "piscine", "mémoire", "carotte", "boisson", "explication", "importance", "repos", "effort", "vacance", "dictionnaire", "poche", "salaire", "chance", "avantage" },
        // 08
        new List<string> { "escalier", "vacance", "science", "effort", "travailleur", "sentiment", "gouvernement", "méthode", "explication", "vaisselle", "différence", "centre", "chance", "raison", "bouteille", "avantage", "sourire", "fromage", "dictionnaire", "intelligence", "côté", "fenêtre", "salaire", "environnement", "confiance", "calendrier", "excuse", "programme", "activité", "façon", "boisson", "chanson", "plaisir", "carotte", "poche", "importance", "reste", "mémoire", "voiture", "piscine", "chaleur", "repos", "tableau", "lecture" },
        // 09
        new List<string> { "plaisir", "poche", "activité", "lecture", "dictionnaire", "boisson", "intelligence", "fromage", "fenêtre", "science", "reste", "travailleur", "bouteille", "chaleur", "repos", "calendrier", "centre", "effort", "programme", "piscine", "confiance", "environnement", "façon", "méthode", "excuse", "voiture", "vacance", "chance", "sentiment", "explication", "gouvernement", "importance", "vaisselle", "sourire", "carotte", "mémoire", "tableau", "salaire", "chanson", "différence", "raison", "escalier", "côté", "avantage" },
        // 10
        new List<string> { "repos", "salaire", "travailleur", "avantage", "piscine", "tableau", "effort", "côté", "dictionnaire", "chanson", "reste", "programme", "mémoire", "fenêtre", "méthode", "carotte", "gouvernement", "chance", "sourire", "science", "voiture", "raison", "chaleur", "vaisselle", "escalier", "activité", "bouteille", "plaisir", "confiance", "intelligence", "calendrier", "boisson", "fromage", "sentiment", "poche", "façon", "centre", "environnement", "importance", "excuse", "explication", "lecture", "différence", "vacance" },
        // 11
        new List<string> { "confiance", "vacance", "fenêtre", "programme", "explication", "bouteille", "carotte", "calendrier", "excuse", "reste", "façon", "science", "activité", "gouvernement", "dictionnaire", "tableau", "plaisir", "effort", "centre", "sentiment", "voiture", "mémoire", "piscine", "environnement", "chaleur", "boisson", "côté", "repos", "raison", "chance", "chanson", "escalier", "salaire", "sourire", "fromage", "poche", "importance", "méthode", "lecture", "différence", "intelligence", "avantage", "travailleur", "vaisselle" },
        // 12
        new List<string> { "façon", "centre", "lecture", "poche", "bouteille", "carotte", "mémoire", "voiture", "méthode", "plaisir", "environnement", "boisson", "chaleur", "reste", "calendrier", "fromage", "vaisselle", "dictionnaire", "activité", "sourire", "repos", "raison", "fenêtre", "chanson", "science", "travailleur", "excuse", "intelligence", "escalier", "tableau", "différence", "effort", "sentiment", "côté", "avantage", "confiance", "gouvernement", "vacance", "explication", "chance", "programme", "salaire", "importance", "piscine" },
        // 13
        new List<string> { "environnement", "gouvernement", "mémoire", "voiture", "vacance", "raison", "plaisir", "programme", "activité", "carotte", "centre", "tableau", "travailleur", "chanson", "avantage", "vaisselle", "côté", "fromage", "boisson", "calendrier", "repos", "excuse", "explication", "différence", "dictionnaire", "poche", "intelligence", "bouteille", "salaire", "escalier", "science", "effort", "façon", "chaleur", "sentiment", "lecture", "reste", "confiance", "fenêtre", "méthode", "piscine", "chance", "importance", "sourire" },
        // 14
        new List<string> { "tableau", "raison", "vacance", "effort", "fromage", "façon", "côté", "avantage", "chance", "fenêtre", "boisson", "bouteille", "science", "piscine", "chanson", "confiance", "plaisir", "environnement", "salaire", "calendrier", "centre", "explication", "mémoire", "sourire", "poche", "programme", "différence", "escalier", "activité", "voiture", "lecture", "chaleur", "sentiment", "méthode", "travailleur", "carotte", "excuse", "intelligence", "repos", "reste", "vaisselle", "gouvernement", "dictionnaire", "importance" },
        // 15
        new List<string> { "piscine", "méthode", "fromage", "vacance", "reste", "carotte", "calendrier", "façon", "importance", "repos", "chanson", "différence", "salaire", "confiance", "raison", "bouteille", "vaisselle", "plaisir", "centre", "poche", "tableau", "dictionnaire", "intelligence", "sentiment", "voiture", "gouvernement", "chance", "avantage", "chaleur", "activité", "mémoire", "sourire", "explication", "lecture", "science", "escalier", "excuse", "environnement", "fenêtre", "boisson", "programme", "côté", "travailleur", "effort" },
        // 16
        new List<string> { "piscine", "calendrier", "dictionnaire", "reste", "côté", "travailleur", "environnement", "boisson", "poche", "salaire", "importance", "sourire", "façon", "fenêtre", "différence", "centre", "intelligence", "méthode", "bouteille", "plaisir", "lecture", "excuse", "chanson", "tableau", "mémoire", "sentiment", "vaisselle", "escalier", "explication", "fromage", "effort", "vacance", "voiture", "activité", "avantage", "science", "gouvernement", "chaleur", "repos", "chance", "confiance", "programme", "raison", "carotte" },
        // 17
        new List<string> { "environnement", "escalier", "travailleur", "vaisselle", "vacance", "carotte", "chance", "importance", "côté", "plaisir", "piscine", "confiance", "intelligence", "chaleur", "chanson", "programme", "voiture", "boisson", "raison", "effort", "dictionnaire", "repos", "reste", "poche", "centre", "activité", "tableau", "sourire", "façon", "gouvernement", "bouteille", "excuse", "explication", "science", "avantage", "fenêtre", "mémoire", "sentiment", "fromage", "calendrier", "différence", "lecture", "méthode", "salaire" },
        // 18
        new List<string> { "lecture", "reste", "importance", "chance", "sourire", "mémoire", "salaire", "différence", "sentiment", "plaisir", "vacance", "vaisselle", "carotte", "environnement", "chanson", "chaleur", "excuse", "activité", "centre", "méthode", "confiance", "escalier", "façon", "intelligence", "boisson", "bouteille", "voiture", "raison", "explication", "repos", "science", "piscine", "fromage", "programme", "travailleur", "gouvernement", "poche", "effort", "dictionnaire", "côté", "fenêtre", "tableau", "calendrier", "avantage" },
        // 19
        new List<string> { "fenêtre", "mémoire", "tableau", "dictionnaire", "sentiment", "travailleur", "sourire", "salaire", "différence", "boisson", "programme", "plaisir", "explication", "poche", "activité", "fromage", "effort", "raison", "importance", "côté", "bouteille", "piscine", "gouvernement", "excuse", "vaisselle", "chaleur", "environnement", "escalier", "centre", "méthode", "façon", "confiance", "reste", "vacance", "carotte", "avantage", "lecture", "science", "voiture", "repos", "chanson", "intelligence", "calendrier", "chance" },
        // 20
        new List<string> { "calendrier", "tableau", "différence", "programme", "excuse", "escalier", "fenêtre", "science", "activité", "plaisir", "confiance", "lecture", "salaire", "chance", "reste", "méthode", "gouvernement", "carotte", "travailleur", "vaisselle", "dictionnaire", "vacance", "environnement", "intelligence", "sourire", "piscine", "centre", "façon", "mémoire", "sentiment", "repos", "chanson", "voiture", "importance", "bouteille", "boisson", "raison", "explication", "avantage", "fromage", "effort", "chaleur", "poche", "côté" },
        // 21
        new List<string> { "chaleur", "reste", "importance", "repos", "gouvernement", "vaisselle", "sourire", "intelligence", "vacance", "plaisir", "façon", "mémoire", "dictionnaire", "différence", "science", "piscine", "méthode", "explication", "sentiment", "excuse", "activité", "chanson", "avantage", "chance", "carotte", "programme", "environnement", "effort", "fromage", "calendrier", "bouteille", "travailleur", "salaire", "poche", "tableau", "côté", "raison", "fenêtre", "lecture", "centre", "escalier", "voiture", "boisson", "confiance" },
        // 22
        new List<string> { "différence", "importance", "effort", "mémoire", "reste", "repos", "vaisselle", "programme", "sentiment", "centre", "fenêtre", "confiance", "voiture", "intelligence", "travailleur", "façon", "raison", "science", "boisson", "fromage", "dictionnaire", "bouteille", "avantage", "piscine", "explication", "escalier", "chaleur", "carotte", "activité", "gouvernement", "sourire", "méthode", "calendrier", "environnement", "côté", "salaire", "poche", "vacance", "tableau", "plaisir", "excuse", "lecture", "chanson", "chance" },
        // 23
        new List<string> { "intelligence", "tableau", "lecture", "méthode", "calendrier", "côté", "raison", "escalier", "environnement", "voiture", "piscine", "chance", "importance", "sourire", "reste", "façon", "science", "vaisselle", "chanson", "explication", "plaisir", "activité", "sentiment", "boisson", "avantage", "effort", "centre", "vacance", "poche", "salaire", "chaleur", "fromage", "différence", "excuse", "fenêtre", "mémoire", "bouteille", "dictionnaire", "travailleur", "gouvernement", "programme", "confiance", "repos", "carotte" },
        // 24
        new List<string> { "intelligence", "chaleur", "vaisselle", "science", "confiance", "lecture", "carotte", "effort", "reste", "dictionnaire", "travailleur", "mémoire", "salaire", "plaisir", "excuse", "importance", "calendrier", "fromage", "environnement", "sentiment", "tableau", "chance", "piscine", "gouvernement", "repos", "différence", "activité", "côté", "escalier", "façon", "raison", "avantage", "programme", "sourire", "bouteille", "chanson", "fenêtre", "poche", "voiture", "centre", "explication", "vacance", "méthode", "boisson" },
        // 25
        new List<string> { "raison", "repos", "calendrier", "gouvernement", "travailleur", "poche", "chance", "importance", "méthode", "environnement", "carotte", "chaleur", "côté", "chanson", "vaisselle", "escalier", "différence", "bouteille", "salaire", "programme", "mémoire", "excuse", "voiture", "piscine", "centre", "vacance", "confiance", "dictionnaire", "explication", "intelligence", "avantage", "fromage", "lecture", "reste", "boisson", "sourire", "science", "fenêtre", "plaisir", "tableau", "sentiment", "effort", "activité", "façon" },
        // 26
        new List<string> { "avantage", "programme", "vaisselle", "chance", "plaisir", "excuse", "vacance", "centre", "raison", "chaleur", "fromage", "boisson", "dictionnaire", "poche", "explication", "travailleur", "sentiment", "sourire", "fenêtre", "façon", "calendrier", "méthode", "repos", "voiture", "science", "lecture", "piscine", "environnement", "différence", "gouvernement", "salaire", "tableau", "chanson", "mémoire", "escalier", "côté", "bouteille", "importance", "confiance", "carotte", "intelligence", "activité", "reste", "effort" },
        // 27
        new List<string> { "centre", "voiture", "confiance", "vaisselle", "fenêtre", "boisson", "intelligence", "avantage", "raison", "calendrier", "escalier", "fromage", "salaire", "bouteille", "dictionnaire", "reste", "poche", "environnement", "piscine", "mémoire", "plaisir", "chanson", "tableau", "repos", "effort", "chance", "méthode", "côté", "programme", "sourire", "sentiment", "vacance", "explication", "excuse", "lecture", "importance", "différence", "gouvernement", "science", "façon", "chaleur", "carotte", "activité", "travailleur" },
        // 28
        new List<string> { "programme", "côté", "salaire", "avantage", "différence", "confiance", "gouvernement", "vacance", "effort", "tableau", "intelligence", "science", "bouteille", "calendrier", "carotte", "chaleur", "reste", "raison", "chanson", "poche", "environnement", "fromage", "activité", "centre", "méthode", "lecture", "escalier", "explication", "excuse", "mémoire", "voiture", "travailleur", "sentiment", "piscine", "chance", "vaisselle", "plaisir", "repos", "sourire", "façon", "fenêtre", "dictionnaire", "importance", "boisson" },
        // 29
        new List<string> { "poche", "fromage", "chance", "explication", "escalier", "intelligence", "travailleur", "dictionnaire", "tableau", "importance", "raison", "avantage", "côté", "piscine", "effort", "gouvernement", "méthode", "reste", "vaisselle", "voiture", "activité", "repos", "mémoire", "sourire", "bouteille", "boisson", "chanson", "sentiment", "environnement", "lecture", "différence", "carotte", "centre", "plaisir", "confiance", "fenêtre", "science", "chaleur", "calendrier", "programme", "vacance", "façon", "salaire", "excuse" },
        // 30
        new List<string> { "reste", "environnement", "voiture", "différence", "chanson", "sourire", "avantage", "raison", "excuse", "fenêtre", "façon", "carotte", "boisson", "importance", "mémoire", "méthode", "programme", "poche", "fromage", "intelligence", "escalier", "gouvernement", "dictionnaire", "vaisselle", "travailleur", "activité", "repos", "chance", "confiance", "tableau", "côté", "explication", "piscine", "plaisir", "calendrier", "effort", "science", "centre", "sentiment", "bouteille", "salaire", "chaleur", "vacance", "lecture" },
        // 31
        new List<string> { "intelligence", "salaire", "chaleur", "raison", "gouvernement", "travailleur", "carotte", "excuse", "fromage", "mémoire", "façon", "tableau", "bouteille", "poche", "côté", "science", "fenêtre", "sourire", "importance", "vaisselle", "lecture", "activité", "environnement", "programme", "dictionnaire", "repos", "avantage", "effort", "sentiment", "chance", "chanson", "différence", "plaisir", "calendrier", "vacance", "reste", "confiance", "centre", "voiture", "méthode", "boisson", "escalier", "explication", "piscine" },
        // 32
        new List<string> { "centre", "reste", "escalier", "fenêtre", "lecture", "programme", "raison", "importance", "excuse", "gouvernement", "activité", "sourire", "différence", "façon", "chanson", "mémoire", "dictionnaire", "chance", "sentiment", "plaisir", "explication", "carotte", "travailleur", "calendrier", "science", "intelligence", "avantage", "confiance", "méthode", "côté", "voiture", "piscine", "fromage", "vacance", "chaleur", "bouteille", "salaire", "effort", "repos", "tableau", "poche", "environnement", "vaisselle", "boisson" },
        // 33
        new List<string> { "centre", "fromage", "escalier", "vacance", "boisson", "reste", "sourire", "programme", "fenêtre", "environnement", "lecture", "avantage", "tableau", "différence", "méthode", "chanson", "poche", "activité", "bouteille", "intelligence", "vaisselle", "plaisir", "façon", "voiture", "confiance", "importance", "carotte", "calendrier", "excuse", "effort", "piscine", "explication", "sentiment", "raison", "science", "mémoire", "dictionnaire", "chance", "repos", "côté", "salaire", "gouvernement", "travailleur", "chaleur" },
        // 34
        new List<string> { "poche", "fenêtre", "bouteille", "méthode", "raison", "piscine", "centre", "reste", "fromage", "carotte", "environnement", "gouvernement", "calendrier", "repos", "intelligence", "façon", "vaisselle", "excuse", "sentiment", "vacance", "activité", "chance", "dictionnaire", "lecture", "programme", "tableau", "différence", "mémoire", "effort", "boisson", "voiture", "chaleur", "sourire", "plaisir", "escalier", "chanson", "importance", "travailleur", "science", "salaire", "avantage", "explication", "côté", "confiance" },
        // 35
        new List<string> { "gouvernement", "vaisselle", "lecture", "vacance", "carotte", "travailleur", "fromage", "repos", "escalier", "bouteille", "confiance", "chance", "sourire", "reste", "voiture", "chanson", "importance", "méthode", "programme", "raison", "poche", "plaisir", "activité", "tableau", "effort", "sentiment", "environnement", "piscine", "façon", "centre", "science", "excuse", "salaire", "côté", "explication", "fenêtre", "mémoire", "intelligence", "différence", "chaleur", "dictionnaire", "boisson", "calendrier", "avantage" },
        // 36
        new List<string> { "travailleur", "intelligence", "science", "repos", "raison", "environnement", "effort", "boisson", "importance", "méthode", "chanson", "poche", "gouvernement", "vacance", "mémoire", "sentiment", "façon", "sourire", "carotte", "reste", "vaisselle", "chaleur", "fenêtre", "piscine", "calendrier", "programme", "plaisir", "bouteille", "avantage", "confiance", "fromage", "côté", "chance", "différence", "activité", "excuse", "centre", "salaire", "voiture", "escalier", "dictionnaire", "explication", "tableau", "lecture" },
        // 37
        new List<string> { "sourire", "excuse", "vaisselle", "chaleur", "repos", "centre", "avantage", "méthode", "reste", "boisson", "dictionnaire", "escalier", "science", "chanson", "fenêtre", "bouteille", "activité", "calendrier", "piscine", "intelligence", "côté", "fromage", "lecture", "carotte", "différence", "raison", "salaire", "mémoire", "effort", "chance", "gouvernement", "tableau", "poche", "explication", "voiture", "environnement", "façon", "confiance", "sentiment", "travailleur", "vacance", "programme", "importance", "plaisir" },
        // 38
        new List<string> { "intelligence", "poche", "façon", "programme", "tableau", "sourire", "vaisselle", "environnement", "chance", "fenêtre", "méthode", "plaisir", "voiture", "vacance", "côté", "salaire", "confiance", "calendrier", "excuse", "piscine", "chaleur", "dictionnaire", "effort", "science", "boisson", "chanson", "différence", "bouteille", "lecture", "avantage", "fromage", "raison", "sentiment", "gouvernement", "mémoire", "travailleur", "centre", "carotte", "escalier", "repos", "reste", "explication", "importance", "activité" },
        // 39
        new List<string> { "programme", "calendrier", "gouvernement", "bouteille", "plaisir", "avantage", "escalier", "excuse", "sentiment", "activité", "carotte", "importance", "voiture", "poche", "chance", "salaire", "centre", "travailleur", "lecture", "sourire", "fromage", "différence", "reste", "effort", "intelligence", "piscine", "façon", "environnement", "confiance", "boisson", "chanson", "repos", "côté", "dictionnaire", "science", "vacance", "méthode", "tableau", "mémoire", "explication", "fenêtre", "chaleur", "vaisselle", "raison" },
        // 40
        new List<string> { "côté", "travailleur", "intelligence", "voiture", "centre", "fromage", "dictionnaire", "tableau", "poche", "carotte", "piscine", "chance", "chaleur", "repos", "différence", "reste", "activité", "lecture", "salaire", "calendrier", "plaisir", "importance", "effort", "sourire", "vaisselle", "excuse", "explication", "programme", "avantage", "chanson", "environnement", "boisson", "science", "gouvernement", "confiance", "vacance", "méthode", "fenêtre", "escalier", "façon", "raison", "bouteille", "mémoire", "sentiment" },
        // 41
        new List<string> { "environnement", "poche", "plaisir", "vacance", "raison", "fenêtre", "carotte", "piscine", "vaisselle", "explication", "tableau", "sentiment", "salaire", "science", "voiture", "avantage", "façon", "chanson", "côté", "sourire", "reste", "centre", "chaleur", "confiance", "repos", "méthode", "escalier", "différence", "chance", "lecture", "boisson", "dictionnaire", "mémoire", "fromage", "programme", "intelligence", "bouteille", "activité", "calendrier", "effort", "travailleur", "gouvernement", "importance", "excuse" },
        // 42
        new List<string> { "activité", "salaire", "environnement", "plaisir", "méthode", "reste", "sentiment", "intelligence", "façon", "travailleur", "science", "bouteille", "gouvernement", "fromage", "lecture", "fenêtre", "avantage", "importance", "dictionnaire", "mémoire", "calendrier", "carotte", "excuse", "repos", "chanson", "différence", "vacance", "chaleur", "raison", "côté", "chance", "confiance", "voiture", "poche", "centre", "vaisselle", "programme", "tableau", "effort", "explication", "piscine", "escalier", "boisson", "sourire" },
        // 43
        new List<string> { "chaleur", "escalier", "gouvernement", "sentiment", "intelligence", "carotte", "vacance", "explication", "effort", "science", "confiance", "bouteille", "différence", "lecture", "salaire", "environnement", "programme", "raison", "côté", "piscine", "travailleur", "méthode", "boisson", "fenêtre", "chanson", "plaisir", "fromage", "tableau", "calendrier", "centre", "poche", "sourire", "chance", "activité", "façon", "mémoire", "repos", "dictionnaire", "importance", "excuse", "avantage", "vaisselle", "voiture", "reste" },
        // 44
        new List<string> { "chanson", "sentiment", "reste", "environnement", "science", "programme", "différence", "repos", "importance", "vacance", "confiance", "gouvernement", "chance", "salaire", "chaleur", "méthode", "poche", "tableau", "escalier", "voiture", "carotte", "bouteille", "vaisselle", "plaisir", "dictionnaire", "fenêtre", "travailleur", "façon", "explication", "boisson", "avantage", "activité", "effort", "excuse", "sourire", "raison", "fromage", "côté", "mémoire", "piscine", "intelligence", "lecture", "centre", "calendrier" },
        // 45
        new List<string> { "science", "tableau", "boisson", "intelligence", "excuse", "chance", "vaisselle", "calendrier", "activité", "repos", "différence", "vacance", "voiture", "dictionnaire", "lecture", "chaleur", "centre", "carotte", "sentiment", "méthode", "façon", "mémoire", "sourire", "côté", "confiance", "poche", "piscine", "fromage", "raison", "environnement", "avantage", "explication", "fenêtre", "salaire", "plaisir", "reste", "chanson", "importance", "gouvernement", "programme", "bouteille", "effort", "travailleur", "escalier" },
        // 46
        new List<string> { "fenêtre", "boisson", "chaleur", "importance", "repos", "différence", "mémoire", "vacance", "science", "gouvernement", "confiance", "effort", "explication", "lecture", "côté", "bouteille", "plaisir", "centre", "calendrier", "vaisselle", "intelligence", "reste", "dictionnaire", "travailleur", "chanson", "activité", "piscine", "excuse", "sentiment", "escalier", "avantage", "poche", "façon", "programme", "raison", "environnement", "voiture", "fromage", "carotte", "sourire", "salaire", "tableau", "méthode", "chance" },
        // 47
        new List<string> { "intelligence", "différence", "travailleur", "centre", "confiance", "calendrier", "sourire", "programme", "salaire", "bouteille", "repos", "méthode", "gouvernement", "poche", "importance", "piscine", "chance", "voiture", "côté", "vaisselle", "reste", "science", "fenêtre", "sentiment", "chanson", "chaleur", "tableau", "dictionnaire", "excuse", "fromage", "environnement", "explication", "vacance", "plaisir", "carotte", "raison", "effort", "avantage", "activité", "lecture", "boisson", "mémoire", "escalier", "façon" },
        // 48
        new List<string> { "plaisir", "gouvernement", "importance", "reste", "voiture", "bouteille", "programme", "activité", "boisson", "dictionnaire", "calendrier", "côté", "chaleur", "raison", "vacance", "lecture", "repos", "fenêtre", "piscine", "avantage", "méthode", "salaire", "poche", "différence", "chanson", "façon", "escalier", "environnement", "sourire", "intelligence", "science", "travailleur", "excuse", "effort", "chance", "tableau", "fromage", "carotte", "sentiment", "centre", "explication", "confiance", "vaisselle", "mémoire" },
        // 49
        new List<string> { "chaleur", "chanson", "escalier", "repos", "carotte", "fromage", "sourire", "travailleur", "reste", "programme", "bouteille", "confiance", "plaisir", "façon", "mémoire", "calendrier", "importance", "explication", "avantage", "lecture", "science", "méthode", "boisson", "côté", "chance", "raison", "activité", "gouvernement", "excuse", "vaisselle", "salaire", "poche", "dictionnaire", "voiture", "fenêtre", "effort", "environnement", "différence", "vacance", "piscine", "tableau", "sentiment", "intelligence", "centre" },
        // 50
        new List<string> { "environnement", "voiture", "bouteille", "raison", "façon", "confiance", "programme", "boisson", "avantage", "dictionnaire", "excuse", "fenêtre", "méthode", "tableau", "côté", "travailleur", "différence", "explication", "vacance", "calendrier", "reste", "chance", "sentiment", "plaisir", "centre", "intelligence", "piscine", "gouvernement", "carotte", "chaleur", "lecture", "activité", "escalier", "poche", "sourire", "fromage", "vaisselle", "salaire", "repos", "chanson", "importance", "effort", "science", "mémoire" },
        // 51
        new List<string> { "salaire", "chaleur", "boisson", "intelligence", "voiture", "vacance", "escalier", "excuse", "calendrier", "méthode", "côté", "effort", "importance", "dictionnaire", "sentiment", "confiance", "bouteille", "reste", "mémoire", "chance", "sourire", "façon", "activité", "avantage", "science", "programme", "tableau", "centre", "environnement", "poche", "plaisir", "raison", "gouvernement", "fromage", "vaisselle", "repos", "explication", "piscine", "lecture", "chanson", "fenêtre", "carotte", "travailleur", "différence" },
        // 52
        new List<string> { "raison", "explication", "escalier", "poche", "méthode", "calendrier", "repos", "mémoire", "intelligence", "avantage", "façon", "tableau", "côté", "dictionnaire", "sourire", "salaire", "gouvernement", "chaleur", "piscine", "activité", "fromage", "différence", "confiance", "reste", "sentiment", "centre", "travailleur", "vacance", "voiture", "environnement", "chanson", "programme", "science", "carotte", "chance", "boisson", "excuse", "effort", "lecture", "fenêtre", "vaisselle", "importance", "plaisir", "bouteille" },
        // 53
        new List<string> { "voiture", "avantage", "bouteille", "science", "raison", "reste", "fenêtre", "escalier", "chanson", "calendrier", "poche", "chaleur", "importance", "différence", "excuse", "sentiment", "sourire", "programme", "vaisselle", "activité", "chance", "boisson", "côté", "plaisir", "salaire", "lecture", "intelligence", "piscine", "carotte", "dictionnaire", "méthode", "effort", "fromage", "travailleur", "explication", "vacance", "gouvernement", "mémoire", "confiance", "repos", "tableau", "environnement", "façon", "centre" },
        // 54
        new List<string> { "salaire", "intelligence", "confiance", "lecture", "raison", "chaleur", "poche", "différence", "repos", "plaisir", "chanson", "sentiment", "voiture", "effort", "gouvernement", "bouteille", "boisson", "sourire", "vacance", "explication", "escalier", "programme", "science", "mémoire", "calendrier", "façon", "piscine", "côté", "importance", "avantage", "reste", "dictionnaire", "vaisselle", "carotte", "chance", "fromage", "méthode", "centre", "activité", "tableau", "fenêtre", "excuse", "environnement", "travailleur" },
        // 55
        new List<string> { "importance", "fromage", "vaisselle", "repos", "dictionnaire", "activité", "reste", "calendrier", "science", "gouvernement", "côté", "travailleur", "méthode", "poche", "bouteille", "sourire", "boisson", "raison", "intelligence", "façon", "effort", "excuse", "carotte", "explication", "confiance", "chance", "fenêtre", "lecture", "voiture", "chanson", "sentiment", "plaisir", "programme", "salaire", "piscine", "avantage", "tableau", "centre", "différence", "mémoire", "vacance", "escalier", "chaleur", "environnement" },
        // 56
        new List<string> { "plaisir", "fenêtre", "programme", "environnement", "intelligence", "lecture", "avantage", "escalier", "côté", "carotte", "travailleur", "vacance", "activité", "centre", "vaisselle", "sentiment", "repos", "fromage", "calendrier", "effort", "dictionnaire", "boisson", "science", "façon", "excuse", "bouteille", "piscine", "méthode", "explication", "tableau", "reste", "mémoire", "chance", "importance", "poche", "différence", "chaleur", "confiance", "voiture", "salaire", "raison", "gouvernement", "chanson", "sourire" },
        // 57
        new List<string> { "lecture", "façon", "chanson", "centre", "carotte", "excuse", "dictionnaire", "importance", "poche", "côté", "vacance", "science", "reste", "travailleur", "activité", "tableau", "intelligence", "fromage", "bouteille", "piscine", "gouvernement", "repos", "sourire", "escalier", "confiance", "programme", "avantage", "chaleur", "environnement", "sentiment", "plaisir", "salaire", "chance", "voiture", "effort", "boisson", "raison", "calendrier", "méthode", "vaisselle", "explication", "fenêtre", "différence", "mémoire" },
        // 58
        new List<string> { "poche", "mémoire", "effort", "dictionnaire", "raison", "lecture", "méthode", "intelligence", "reste", "chaleur", "sentiment", "vacance", "côté", "gouvernement", "fenêtre", "programme", "importance", "carotte", "explication", "tableau", "travailleur", "différence", "activité", "salaire", "calendrier", "façon", "chanson", "fromage", "sourire", "chance", "plaisir", "boisson", "voiture", "escalier", "science", "avantage", "excuse", "environnement", "confiance", "repos", "bouteille", "centre", "piscine", "vaisselle" },
        // 59
        new List<string> { "activité", "explication", "avantage", "escalier", "plaisir", "méthode", "science", "sentiment", "poche", "sourire", "bouteille", "mémoire", "reste", "chance", "boisson", "gouvernement", "façon", "environnement", "tableau", "lecture", "fenêtre", "repos", "centre", "dictionnaire", "confiance", "différence", "vaisselle", "vacance", "intelligence", "voiture", "travailleur", "côté", "effort", "programme", "importance", "carotte", "chaleur", "excuse", "raison", "chanson", "fromage", "salaire", "piscine", "calendrier" },
        // 60
        new List<string> { "fromage", "confiance", "activité", "sentiment", "carotte", "boisson", "bouteille", "lecture", "gouvernement", "plaisir", "piscine", "chaleur", "mémoire", "reste", "calendrier", "différence", "avantage", "sourire", "méthode", "chanson", "escalier", "vacance", "côté", "fenêtre", "importance", "programme", "environnement", "façon", "voiture", "chance", "raison", "salaire", "excuse", "poche", "explication", "travailleur", "effort", "dictionnaire", "tableau", "centre", "intelligence", "vaisselle", "science", "repos" },
        // 61
        new List<string> { "avantage", "boisson", "méthode", "sentiment", "travailleur", "chaleur", "escalier", "bouteille", "effort", "plaisir", "carotte", "importance", "chanson", "fromage", "programme", "calendrier", "vaisselle", "différence", "sourire", "dictionnaire", "intelligence", "excuse", "lecture", "mémoire", "voiture", "salaire", "reste", "science", "confiance", "environnement", "vacance", "activité", "côté", "piscine", "façon", "poche", "chance", "raison", "fenêtre", "centre", "gouvernement", "repos", "tableau", "explication" },
        // 62
        new List<string> { "gouvernement", "science", "plaisir", "sentiment", "environnement", "centre", "fromage", "repos", "importance", "vaisselle", "avantage", "intelligence", "explication", "raison", "vacance", "différence", "poche", "excuse", "chanson", "chance", "côté", "confiance", "calendrier", "activité", "programme", "fenêtre", "salaire", "bouteille", "façon", "méthode", "lecture", "carotte", "tableau", "mémoire", "reste", "chaleur", "voiture", "boisson", "sourire", "travailleur", "escalier", "piscine", "effort", "dictionnaire" },
        // 63
        new List<string> { "confiance", "science", "travailleur", "piscine", "vaisselle", "environnement", "salaire", "carotte", "côté", "explication", "lecture", "calendrier", "façon", "boisson", "chaleur", "effort", "avantage", "fenêtre", "bouteille", "chance", "poche", "raison", "méthode", "repos", "tableau", "escalier", "intelligence", "sentiment", "activité", "mémoire", "reste", "voiture", "sourire", "chanson", "programme", "dictionnaire", "vacance", "importance", "gouvernement", "fromage", "centre", "excuse", "plaisir", "différence" },
        // 64
        new List<string> { "boisson", "calendrier", "mémoire", "poche", "programme", "dictionnaire", "travailleur", "fenêtre", "lecture", "salaire", "effort", "gouvernement", "vacance", "différence", "reste", "confiance", "environnement", "importance", "raison", "centre", "côté", "fromage", "intelligence", "sentiment", "méthode", "vaisselle", "science", "chanson", "explication", "bouteille", "repos", "chance", "piscine", "carotte", "voiture", "activité", "excuse", "façon", "escalier", "avantage", "tableau", "chaleur", "plaisir", "sourire" },
        // 65
        new List<string> { "environnement", "activité", "escalier", "vacance", "voiture", "sentiment", "poche", "fenêtre", "centre", "mémoire", "méthode", "reste", "avantage", "chaleur", "plaisir", "raison", "fromage", "programme", "importance", "lecture", "différence", "salaire", "vaisselle", "confiance", "tableau", "façon", "gouvernement", "science", "chance", "carotte", "dictionnaire", "intelligence", "effort", "travailleur", "explication", "piscine", "boisson", "bouteille", "chanson", "côté", "repos", "calendrier", "sourire", "excuse" },
        // 66
        new List<string> { "fromage", "escalier", "plaisir", "voiture", "centre", "fenêtre", "science", "chanson", "raison", "vacance", "façon", "poche", "activité", "environnement", "chaleur", "sourire", "avantage", "intelligence", "carotte", "gouvernement", "dictionnaire", "confiance", "salaire", "sentiment", "méthode", "travailleur", "reste", "tableau", "piscine", "repos", "côté", "explication", "chance", "calendrier", "excuse", "lecture", "boisson", "différence", "programme", "bouteille", "mémoire", "vaisselle", "importance", "effort" },
        // 67
        new List<string> { "centre", "mémoire", "poche", "sentiment", "chance", "chaleur", "fromage", "programme", "tableau", "explication", "piscine", "effort", "environnement", "sourire", "importance", "travailleur", "différence", "façon", "excuse", "fenêtre", "bouteille", "boisson", "repos", "vacance", "dictionnaire", "côté", "salaire", "reste", "calendrier", "avantage", "chanson", "confiance", "science", "plaisir", "méthode", "gouvernement", "raison", "intelligence", "carotte", "voiture", "activité", "lecture", "vaisselle", "escalier" },
        // 68
        new List<string> { "sourire", "voiture", "côté", "dictionnaire", "poche", "tableau", "programme", "chance", "différence", "piscine", "repos", "effort", "intelligence", "confiance", "gouvernement", "travailleur", "bouteille", "façon", "importance", "fromage", "lecture", "vaisselle", "chanson", "sentiment", "calendrier", "explication", "avantage", "excuse", "science", "méthode", "chaleur", "activité", "mémoire", "salaire", "raison", "fenêtre", "plaisir", "centre", "reste", "environnement", "vacance", "boisson", "carotte", "escalier" },
        // 69
        new List<string> { "excuse", "science", "vacance", "travailleur", "chaleur", "sourire", "fenêtre", "façon", "carotte", "dictionnaire", "repos", "tableau", "calendrier", "centre", "explication", "reste", "salaire", "fromage", "confiance", "plaisir", "programme", "escalier", "activité", "méthode", "piscine", "environnement", "côté", "poche", "importance", "raison", "effort", "mémoire", "avantage", "chanson", "sentiment", "intelligence", "gouvernement", "boisson", "différence", "bouteille", "lecture", "chance", "voiture", "vaisselle" },
        // 70
        new List<string> { "tableau", "effort", "piscine", "différence", "centre", "programme", "environnement", "travailleur", "explication", "repos", "vacance", "activité", "reste", "chance", "lecture", "poche", "confiance", "vaisselle", "carotte", "voiture", "raison", "chanson", "bouteille", "sentiment", "salaire", "méthode", "sourire", "importance", "avantage", "escalier", "calendrier", "boisson", "fenêtre", "dictionnaire", "science", "chaleur", "gouvernement", "façon", "intelligence", "excuse", "fromage", "mémoire", "plaisir", "côté" },
        // 71
        new List<string> { "chance", "voiture", "boisson", "programme", "effort", "sourire", "science", "raison", "explication", "intelligence", "vacance", "sentiment", "travailleur", "fenêtre", "reste", "centre", "chanson", "activité", "mémoire", "côté", "avantage", "méthode", "importance", "salaire", "fromage", "poche", "lecture", "calendrier", "chaleur", "dictionnaire", "bouteille", "piscine", "excuse", "façon", "différence", "environnement", "gouvernement", "escalier", "vaisselle", "confiance", "plaisir", "repos", "tableau", "carotte" },
        // 72
        new List<string> { "côté", "façon", "poche", "bouteille", "science", "intelligence", "raison", "tableau", "repos", "carotte", "voiture", "plaisir", "reste", "effort", "avantage", "calendrier", "sentiment", "piscine", "excuse", "confiance", "mémoire", "travailleur", "boisson", "chanson", "dictionnaire", "chance", "gouvernement", "fenêtre", "lecture", "explication", "salaire", "escalier", "centre", "fromage", "vacance", "importance", "programme", "activité", "environnement", "chaleur", "méthode", "sourire", "vaisselle", "différence" },
        // 73
        new List<string> { "voiture", "raison", "différence", "effort", "méthode", "boisson", "science", "côté", "gouvernement", "explication", "poche", "vaisselle", "centre", "activité", "fromage", "chaleur", "repos", "chance", "escalier", "sentiment", "dictionnaire", "travailleur", "environnement", "plaisir", "programme", "lecture", "piscine", "mémoire", "excuse", "importance", "calendrier", "tableau", "confiance", "chanson", "vacance", "bouteille", "fenêtre", "carotte", "façon", "reste", "intelligence", "salaire", "avantage", "sourire" },
        // 74
        new List<string> { "calendrier", "piscine", "science", "vacance", "côté", "tableau", "chaleur", "fenêtre", "chanson", "reste", "programme", "plaisir", "lecture", "repos", "environnement", "fromage", "boisson", "escalier", "intelligence", "centre", "travailleur", "confiance", "méthode", "gouvernement", "raison", "chance", "façon", "dictionnaire", "voiture", "sourire", "activité", "importance", "vaisselle", "salaire", "poche", "mémoire", "effort", "sentiment", "excuse", "explication", "carotte", "bouteille", "différence", "avantage" },
        // 75
        new List<string> { "confiance", "bouteille", "salaire", "chanson", "façon", "voiture", "science", "reste", "sentiment", "poche", "fromage", "mémoire", "effort", "programme", "importance", "centre", "fenêtre", "repos", "chaleur", "chance", "raison", "calendrier", "vacance", "environnement", "excuse", "tableau", "carotte", "méthode", "sourire", "explication", "activité", "avantage", "gouvernement", "intelligence", "différence", "dictionnaire", "vaisselle", "escalier", "lecture", "boisson", "plaisir", "piscine", "travailleur", "côté" },
        // 76
        new List<string> { "mémoire", "sourire", "chaleur", "travailleur", "effort", "côté", "chance", "intelligence", "centre", "confiance", "lecture", "différence", "fenêtre", "boisson", "sentiment", "environnement", "dictionnaire", "importance", "gouvernement", "programme", "tableau", "avantage", "excuse", "bouteille", "méthode", "vacance", "vaisselle", "chanson", "piscine", "raison", "science", "salaire", "activité", "reste", "repos", "plaisir", "explication", "façon", "escalier", "carotte", "fromage", "voiture", "calendrier", "poche" },
        // 77
        new List<string> { "intelligence", "chance", "raison", "gouvernement", "centre", "fromage", "environnement", "boisson", "vaisselle", "programme", "piscine", "lecture", "avantage", "excuse", "tableau", "vacance", "façon", "chaleur", "escalier", "méthode", "explication", "reste", "différence", "calendrier", "repos", "confiance", "voiture", "carotte", "salaire", "chanson", "bouteille", "dictionnaire", "côté", "activité", "travailleur", "mémoire", "poche", "effort", "sentiment", "plaisir", "fenêtre", "sourire", "science", "importance" },
        // 78
        new List<string> { "plaisir", "poche", "tableau", "boisson", "raison", "piscine", "côté", "méthode", "dictionnaire", "sentiment", "différence", "chance", "confiance", "chanson", "avantage", "explication", "excuse", "vacance", "façon", "science", "calendrier", "reste", "escalier", "fromage", "vaisselle", "sourire", "lecture", "chaleur", "centre", "importance", "activité", "voiture", "intelligence", "effort", "mémoire", "salaire", "travailleur", "bouteille", "gouvernement", "environnement", "carotte", "repos", "programme", "fenêtre" },
        // 79
        new List<string> { "carotte", "chanson", "science", "avantage", "plaisir", "escalier", "activité", "excuse", "côté", "chance", "fenêtre", "calendrier", "vacance", "reste", "piscine", "intelligence", "sentiment", "chaleur", "méthode", "dictionnaire", "importance", "explication", "fromage", "environnement", "tableau", "gouvernement", "travailleur", "lecture", "salaire", "bouteille", "vaisselle", "voiture", "centre", "effort", "confiance", "raison", "différence", "mémoire", "façon", "repos", "programme", "sourire", "boisson", "poche" },
        // 80
        new List<string> { "calendrier", "méthode", "boisson", "gouvernement", "intelligence", "poche", "vaisselle", "excuse", "explication", "plaisir", "programme", "importance", "salaire", "avantage", "carotte", "environnement", "lecture", "piscine", "voiture", "fromage", "travailleur", "confiance", "repos", "mémoire", "escalier", "raison", "dictionnaire", "façon", "tableau", "chanson", "chance", "sourire", "sentiment", "vacance", "science", "reste", "côté", "fenêtre", "effort", "différence", "bouteille", "chaleur", "centre", "activité" },
        // 81
        new List<string> { "chance", "plaisir", "escalier", "repos", "chaleur", "activité", "différence", "avantage", "piscine", "vacance", "salaire", "bouteille", "environnement", "méthode", "sentiment", "vaisselle", "façon", "confiance", "sourire", "tableau", "reste", "gouvernement", "centre", "lecture", "carotte", "chanson", "programme", "voiture", "science", "excuse", "importance", "mémoire", "calendrier", "boisson", "intelligence", "fromage", "poche", "dictionnaire", "raison", "effort", "travailleur", "fenêtre", "explication", "côté" },
        // 82
        new List<string> { "voiture", "façon", "mémoire", "dictionnaire", "différence", "chaleur", "bouteille", "explication", "activité", "vaisselle", "chanson", "poche", "tableau", "boisson", "excuse", "intelligence", "fenêtre", "repos", "sentiment", "centre", "avantage", "escalier", "environnement", "raison", "piscine", "salaire", "gouvernement", "plaisir", "programme", "reste", "science", "fromage", "confiance", "calendrier", "méthode", "carotte", "côté", "lecture", "vacance", "chance", "travailleur", "sourire", "importance", "effort" },
        // 83
        new List<string> { "explication", "dictionnaire", "calendrier", "tableau", "vacance", "différence", "excuse", "boisson", "méthode", "avantage", "gouvernement", "travailleur", "confiance", "salaire", "repos", "chance", "programme", "voiture", "sourire", "côté", "fenêtre", "mémoire", "escalier", "sentiment", "plaisir", "environnement", "chaleur", "science", "activité", "façon", "raison", "importance", "lecture", "carotte", "chanson", "reste", "centre", "vaisselle", "poche", "piscine", "intelligence", "fromage", "bouteille", "effort" },
        // 84
        new List<string> { "boisson", "effort", "chanson", "calendrier", "activité", "méthode", "chance", "fromage", "explication", "reste", "chaleur", "travailleur", "piscine", "tableau", "sentiment", "lecture", "excuse", "vaisselle", "mémoire", "science", "voiture", "avantage", "gouvernement", "fenêtre", "dictionnaire", "façon", "plaisir", "environnement", "sourire", "salaire", "différence", "vacance", "escalier", "importance", "centre", "bouteille", "poche", "repos", "carotte", "confiance", "intelligence", "programme", "raison", "côté" },
        // 85
        new List<string> { "sentiment", "salaire", "confiance", "reste", "activité", "lecture", "carotte", "vacance", "travailleur", "boisson", "avantage", "gouvernement", "sourire", "piscine", "poche", "escalier", "mémoire", "chaleur", "repos", "bouteille", "vaisselle", "chance", "plaisir", "voiture", "façon", "différence", "méthode", "programme", "tableau", "explication", "science", "raison", "effort", "excuse", "environnement", "fenêtre", "intelligence", "centre", "fromage", "chanson", "calendrier", "côté", "importance", "dictionnaire" },
        // 86
        new List<string> { "sourire", "vacance", "sentiment", "voiture", "chance", "environnement", "reste", "mémoire", "chanson", "fenêtre", "lecture", "boisson", "côté", "piscine", "intelligence", "travailleur", "plaisir", "différence", "vaisselle", "programme", "tableau", "centre", "bouteille", "raison", "fromage", "avantage", "effort", "importance", "carotte", "poche", "explication", "méthode", "calendrier", "escalier", "repos", "science", "façon", "gouvernement", "activité", "excuse", "dictionnaire", "salaire", "chaleur", "confiance" },
        // 87
        new List<string> { "plaisir", "côté", "chance", "façon", "effort", "importance", "calendrier", "activité", "vaisselle", "intelligence", "centre", "poche", "boisson", "salaire", "carotte", "mémoire", "raison", "avantage", "excuse", "voiture", "bouteille", "tableau", "explication", "confiance", "environnement", "science", "gouvernement", "escalier", "vacance", "repos", "fromage", "dictionnaire", "lecture", "sourire", "programme", "travailleur", "sentiment", "chaleur", "reste", "différence", "méthode", "piscine", "chanson", "fenêtre" },
        // 88
        new List<string> { "piscine", "repos", "chanson", "voiture", "confiance", "poche", "activité", "lecture", "dictionnaire", "raison", "chaleur", "excuse", "reste", "différence", "bouteille", "gouvernement", "sourire", "carotte", "boisson", "calendrier", "sentiment", "effort", "science", "salaire", "méthode", "façon", "côté", "chance", "vaisselle", "fenêtre", "fromage", "vacance", "mémoire", "centre", "plaisir", "explication", "importance", "avantage", "programme", "escalier", "environnement", "intelligence", "tableau", "travailleur" },
        // 89
        new List<string> { "raison", "sourire", "poche", "gouvernement", "plaisir", "escalier", "mémoire", "repos", "dictionnaire", "différence", "avantage", "excuse", "importance", "vaisselle", "chanson", "fromage", "voiture", "boisson", "bouteille", "activité", "programme", "tableau", "effort", "environnement", "carotte", "côté", "science", "chaleur", "lecture", "confiance", "explication", "piscine", "reste", "centre", "travailleur", "chance", "intelligence", "calendrier", "sentiment", "salaire", "méthode", "vacance", "fenêtre", "façon" },
        // 90
        new List<string> { "travailleur", "boisson", "chaleur", "programme", "fromage", "calendrier", "bouteille", "repos", "chance", "explication", "plaisir", "centre", "fenêtre", "escalier", "poche", "tableau", "environnement", "activité", "vacance", "chanson", "gouvernement", "intelligence", "science", "lecture", "façon", "côté", "vaisselle", "reste", "effort", "dictionnaire", "sourire", "méthode", "carotte", "importance", "excuse", "piscine", "voiture", "confiance", "sentiment", "raison", "mémoire", "salaire", "différence", "avantage" },
        // 91
        new List<string> { "calendrier", "environnement", "chance", "raison", "repos", "reste", "mémoire", "fenêtre", "intelligence", "explication", "science", "tableau", "méthode", "sentiment", "importance", "confiance", "activité", "côté", "piscine", "effort", "sourire", "poche", "façon", "avantage", "lecture", "fromage", "voiture", "programme", "vacance", "vaisselle", "gouvernement", "plaisir", "excuse", "bouteille", "boisson", "différence", "travailleur", "dictionnaire", "chaleur", "centre", "carotte", "salaire", "escalier", "chanson" },
        // 92
        new List<string> { "activité", "côté", "lecture", "science", "repos", "sentiment", "chance", "effort", "programme", "excuse", "vacance", "gouvernement", "piscine", "bouteille", "boisson", "sourire", "travailleur", "vaisselle", "poche", "environnement", "importance", "dictionnaire", "méthode", "plaisir", "carotte", "escalier", "centre", "mémoire", "calendrier", "salaire", "fromage", "fenêtre", "chaleur", "explication", "chanson", "intelligence", "voiture", "raison", "tableau", "différence", "confiance", "reste", "avantage", "façon" },
        // 93
        new List<string> { "différence", "lecture", "vaisselle", "côté", "travailleur", "tableau", "carotte", "escalier", "repos", "activité", "environnement", "centre", "intelligence", "voiture", "confiance", "fenêtre", "reste", "calendrier", "raison", "chance", "boisson", "excuse", "méthode", "dictionnaire", "sentiment", "bouteille", "sourire", "importance", "chaleur", "façon", "salaire", "gouvernement", "mémoire", "programme", "vacance", "effort", "fromage", "explication", "plaisir", "chanson", "piscine", "avantage", "science", "poche" },
        // 94
        new List<string> { "science", "fenêtre", "environnement", "travailleur", "explication", "centre", "salaire", "côté", "sourire", "excuse", "mémoire", "confiance", "calendrier", "bouteille", "carotte", "raison", "chanson", "gouvernement", "dictionnaire", "intelligence", "avantage", "lecture", "méthode", "différence", "programme", "vaisselle", "chaleur", "fromage", "sentiment", "escalier", "boisson", "voiture", "vacance", "effort", "reste", "plaisir", "façon", "tableau", "chance", "repos", "activité", "piscine", "poche", "importance" },
        // 95
        new List<string> { "tableau", "fromage", "chaleur", "environnement", "salaire", "fenêtre", "façon", "raison", "poche", "dictionnaire", "confiance", "gouvernement", "lecture", "méthode", "piscine", "reste", "activité", "mémoire", "carotte", "chanson", "sourire", "bouteille", "vacance", "sentiment", "travailleur", "différence", "voiture", "explication", "intelligence", "chance", "effort", "plaisir", "côté", "boisson", "science", "vaisselle", "escalier", "centre", "repos", "excuse", "importance", "avantage", "programme", "calendrier" },
        // 96
        new List<string> { "sentiment", "sourire", "salaire", "mémoire", "façon", "vacance", "centre", "programme", "piscine", "effort", "science", "excuse", "environnement", "méthode", "escalier", "poche", "côté", "travailleur", "dictionnaire", "intelligence", "vaisselle", "raison", "fromage", "importance", "fenêtre", "chaleur", "activité", "boisson", "gouvernement", "chance", "voiture", "bouteille", "repos", "différence", "carotte", "calendrier", "explication", "avantage", "chanson", "confiance", "tableau", "lecture", "reste", "plaisir" },
        // 97
        new List<string> { "chaleur", "chanson", "calendrier", "importance", "dictionnaire", "explication", "façon", "science", "carotte", "confiance", "sentiment", "raison", "fenêtre", "bouteille", "repos", "fromage", "tableau", "effort", "piscine", "excuse", "mémoire", "boisson", "avantage", "reste", "escalier", "activité", "vaisselle", "intelligence", "sourire", "centre", "environnement", "salaire", "côté", "différence", "poche", "travailleur", "vacance", "programme", "voiture", "lecture", "méthode", "chance", "plaisir", "gouvernement" },
        // 98
        new List<string> { "gouvernement", "confiance", "bouteille", "sourire", "méthode", "lecture", "activité", "mémoire", "salaire", "programme", "science", "centre", "fenêtre", "poche", "différence", "plaisir", "reste", "vaisselle", "repos", "boisson", "carotte", "explication", "effort", "chance", "dictionnaire", "raison", "environnement", "excuse", "chaleur", "travailleur", "vacance", "importance", "calendrier", "tableau", "escalier", "avantage", "voiture", "chanson", "intelligence", "fromage", "façon", "sentiment", "piscine", "côté" },
        // 99
        new List<string> { "différence", "escalier", "centre", "effort", "chanson", "tableau", "sourire", "science", "sentiment", "fenêtre", "vaisselle", "dictionnaire", "boisson", "raison", "lecture", "activité", "chaleur", "carotte", "plaisir", "intelligence", "calendrier", "programme", "confiance", "explication", "côté", "façon", "salaire", "vacance", "repos", "environnement", "méthode", "chance", "importance", "avantage", "poche", "fromage", "travailleur", "mémoire", "voiture", "bouteille", "piscine", "gouvernement", "excuse", "reste" },
    };
    public static int CurrentIndex = 0;
}